# EdgeDNS configuration

[upstream]
# Type of upstream servers: "resolver" or "authoritative"
type = "resolver"

# Upstream servers
servers = ["8.8.8.8:53", "8.8.4.4:53"]

# Load balancing/failover strategy: "uniform", "fallback" or "minload"
strategy = "uniform"

# Max failures before marking a server as temporarily unresponsive
max_failures = 3


[cache]
# Max number of cached entries
max_items = 250000

# Minimum TTL - Records with a TTL shorter than that one will not trigger a
# cache refresh. Increasing that value increases the cache hit ratio,
# improves reliability and reduces the load on upstream servers, but zones
# changes will obviously require more time to be visible by clients.
min_ttl = 60

# Maximum TTL - Records with a TTL larger than that one will be refreshed no
# matter what. These usually come from misconfigured zones.
max_ttl = 86400


[network]
# Max number of UDP ports to use for outgoing connections, up to 64511
udp_ports = 8

# Listen address
listen = "0.0.0.0:53"


[webservice]
# Change to `true` in order to start the webservice
enabled = false

# Webservice address for Prometheus. Path will be /metrics
listen = "0.0.0.0:9090"


[dnstap]
# Change to `true` in order to enable dnstap-based logging
enabled = false

# Backlog
# backlog = 4096

# UNIX socket path, relative to the chroot directory
socket_path = "/var/run/edgedns.dnstap"

# Identity (optional) - Should be set to the name of the host
# identity = "hostname"

# Version (optional) - Should be set to the software name
version = "EdgeDNS"


[global]
# User name to drop privileges to
# user = "_edgedns"

# Group to drop privileges to, if not the primary group of the user
# group = "_edgedns"

# Directory to chroot() into
# chroot = "/var/empty"

# Number of threads handling client queries received over UDP
# More than 1 is rarely required. Set to 0 to disable UDP.
threads_udp = 1

# Number of threads handling client queries received over TCP
# More than 1 is very rarely required. Set to 0 to disable TCP.
threads_tcp = 1

# Max number of clients waiting for a response
max_waiting_clients = 1000000

# Max number of inflight queries
max_active_queries = 100000

# Max number of clients waiting for a response to the same query
max_clients_waiting_for_query = 1000
